# Generated by Django 4.2.1 on 2023-05-29 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
